@startmindmap

+ distributed\nsystem
++ communication

+++ messaging\nmodel

++++ point-to-point
+++++ ...

++++ broadcast
+++++ ...

++++ queue

+++++ realted\npatterns
++++++_ event-driven
++++++_ saga pattern
++++++_ publish–subscribe
++++++_ CQRS

+++++ message broker
+++++ message bus

+++++ deployment
++++++_ cloud
++++++_ onprem

+++++ advantages
++++++ decoupling
++++++ load bufffering\n or throttling

++++++ streaming
++++++ durability

++++++ security
+++++++_ encryption
+++++++_ authorization
+++++++_ authentication
+++++++_ audit
+++++++_ integrity guarantees

++++++ delivery guarantee
++++++ scale
+++++++_ load balancing

++++++ complex event processing
+++++++_ validation
+++++++_ transformation
+++++++_ filtering
+++++++_ routing
+++++++_ broadcast and multicast
+++++++_ transaction management

+++ type
++++_ sync
++++_ aync

+++ protocols
++++_ AMQP
++++_ STOMP
++++_ XMPP
++++_ JMS
++++_ MQTT
++++_ HTTP

++ architectures
+++_ client–server
+++_ n-tier
+++_ peer-to-peer
+++_ microservices
+++_ data-centered

@endmindmap
