@startmindmap

+ distributed\nsystem
++ communication

+++ messaging\nmodel

++++ point-to-point
+++++ ...

++++ broadcast
+++++ ...

++++ queue

+++++ realted\npatterns
++++++_ event-driven
++++++_ saga pattern
++++++_ publish–subscribe
++++++_ CQRS

+++++ message broker

+++++ message bus

+++++ deployment
++++++_ cloud
++++++_ onprem


+++++ advantages
++++++_ decoupling
++++++_ bufffering
++++++_ transaction management
++++++_ routing
++++++_ broadcast and multicast
++++++_ streaming
++++++_ validation
++++++_ transformation
++++++_ filtering
++++++_ durability
++++++_ security
++++++_ delivery guarantee
++++++_ scale

+++ type
++++_ sync
++++_ aync

+++ protocols
++++_ AMQP
++++_ STOMP
++++_ XMPP
++++_ JMS
++++_ MQTT
++++_ HTTP

++ architectures
+++_ client–server
+++_ n-tier
+++_ peer-to-peer
+++_ microservices
+++_ data-centered

@endmindmap
