@startmindmap

+ distributed\nsystem
++ communication

+++ messaging\nmodel

++++ point-to-point
+++++ ...

++++ broadcast
+++++ ...

++++ queue

+++++ realted\npatterns
++++++_ event-driven\napproach
++++++_ saga pattern
++++++_ publish–subscribe
++++++_ CQRS

+++++ message broker

+++++ message bus

+++++ advantages
++++++_ decoupling
++++++_ bufffering
++++++_ transaction management
++++++_ routing
++++++_ broadcast and multicast
++++++_ streaming
++++++_ validation
++++++_ transformation
++++++_ filtering
++++++_ persistance
++++++_ delivery guarantee
++++++_ scale

+++ type
++++_ sync
++++_ aync

++ architectures
+++_ client–server
+++_ n-tier
+++_ peer-to-peer
+++_ microservices

@endmindmap
